# Generated by Django 4.2.7 on 2023-11-16 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.ImageField(default='', upload_to='media/%y/%m/%d'),
        ),
    ]
