# Generated by Django 4.2.7 on 2023-11-16 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0002_food_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(default='', upload_to='%y/%m/%d'),
        ),
    ]
