# Generated by Django 4.2.7 on 2023-11-16 12:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0003_alter_food_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='amount',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='food',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
