# Generated by Django 4.2.7 on 2023-11-17 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0004_rename_amount_food_quantity_food_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='foods',
            field=models.ManyToManyField(through='billapp.BillOrders', to='billapp.food'),
        ),
        migrations.AddField(
            model_name='food',
            name='bills',
            field=models.ManyToManyField(through='billapp.BillOrders', to='billapp.bill'),
        ),
        migrations.AlterField(
            model_name='billorders',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='billapp.bill'),
        ),
        migrations.AlterField(
            model_name='billorders',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='billapp.food'),
        ),
    ]
