# Generated by Django 4.2.7 on 2023-11-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0006_remove_billorders_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='client',
            field=models.CharField(default='', max_length=50),
        ),
    ]
